---
RecipeFormatVersion: "2020-01-25"
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "This component adds a service that exposes GGv2 IPC socket over TCP"
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentDependencies:
  ggv2.nomad.proxy.tes:
    VersionRequirement: ^1.0.0
    DependencyType: SOFT
Manifests:
  - Platform:
      os: linux
    Lifecycle:
      Install:
        RequiresPrivilege: true
        Script: |-
          cat > nomad-docker-s3-example.nomad <<EOF
          job "nomad-docker-s3-example" {
            datacenters = ["dc1"]
            type = "service"

            group "s3-example-group" {
            
              constraint {
                attribute = "\${meta.greengrass_ipc}"
                operator  = "="
                value     = "client"
              }

              task "s3-example-task" {
                driver = "docker"
                config {
                  image = "{AWS_ACCOUNT_ID}.dkr.ecr.{AWS_REGION}.amazonaws.com/{COMPONENT_NAME_DIR}:latest"
                  network_mode = "host"
                }
                env {
                  AWS_CONTAINER_CREDENTIALS_FULL_URI = "$AWS_CONTAINER_CREDENTIALS_FULL_URI"
                  AWS_REGION = "$AWS_REGION"
                  AWS_CONTAINER_AUTHORIZATION_TOKEN = "$AWS_CONTAINER_AUTHORIZATION_TOKEN"
                }
              }
            }
          }
          EOF
          NOMAD_ADDR=http://127.0.0.1:8080 nomad job run nomad-docker-s3-example.nomad || true


